# Generated by Django 6.0.7 on 2026-07-20 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('status', models.CharField(default='NOTSTARTED', max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('assigned', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
